spring:
  application:
    name: user-management-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
authorization:
  enabled: true
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 43200000
server:
  port: 8010
  servlet:
    context-path: /api